### ISSUE TITLE
Dart Package

### ISSUE THREAD

**Issue by zeucxb** [ChangeFinance/zendesk-flutter-plugin#16]
Hi, thank you for the awesome work, I'll use this to create a Zendesk chat component.

Do u intends to publish it as a Dart Package? It'ld be great.

**Comment by zeucxb** [comment]
@wtakashi @mustafatufan @sudoFerraz I really need to use it in my project, do you have plans to publish? If not, I'll fork and publish on http://pub.dev/ ok?

**Comment by zeucxb** [comment]
Ok, I'll fork it and publish. Because I need to publish my chat 😕

Please contact me when see this message.

**Comment by zeucxb** [comment]
Please, don't get me wrong. You don't have a `LICENSE`. And, I'm trying to contact you without success.

I'm here to help, but really need this.

Thank you for the awesome work, and please contact me.

**Comment by zeucxb** [comment]
I just saw that @sogurtsov made some releases, so I'll pray and wait until tomorrow for some response. I really prefer that you publish this package. Please, help me.

**Comment by zeucxb** [comment]
I made some changes to publish, so I'll open a PR.

**Comment by zeucxb** [comment]
PR opened https://github.com/ChangeFinance/zendesk-flutter-plugin/pull/17

**Comment by sudoFerraz** [comment]
Hi @zeucxb ! Thanks for reaching out, we were in some chaos recently and haven't seen your issue being opened, I'm very glad to see that we can give back to the community right now :D I will kindly review your PR and we will be publishing it today 💯
