### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by zeucxb** [ChangeFinance/zendesk-flutter-plugin#23]
I don't know exactly why, but you use `io.flutter.app.FlutterFragmentActivity` in `MainActivity` and `implementation 'com.android.support:support-v4:28.0.0'` in Graddle. What is causing conflict on AndroidX.

<img width="1552" alt="Screen Shot 2019-10-25 at 01 43 34" src="https://user-images.githubusercontent.com/11702749/67543722-1d2f2880-f6c9-11e9-9266-b079656e1f44.png">

**Comment by nashihu** [comment]
any update?

**Comment by sudoFerraz** [comment]
@kaarelsoot I'm assigning this to you, can you please provide more info about how you solved this issue when integrating codecov and the flutter drivers for tests. I guess we already committed the code to fix it but there is a certain channel of flutter that needs to be used correct? If you don't remember, just give me the info that you have and I will pick this up to help @nashihu and @zeucxb. Ty

**Comment by sudoFerraz** [comment]
AndroidX support tested and works fine
@zeucxb Can you please provide flutter doctor output ?
Also please provide which release version you are using zendesk-flutter-plugin on pubspec.yaml

**Comment by sudoFerraz** [comment]
Closing this as no answers were provided, please comment and I'll gladly reopen it
