### ISSUE TITLE
MainActivity.java:11: error: incompatible types: MainActivity cannot be converted to PluginRegistry

### ISSUE THREAD

**Issue by lkettwig** [ChangeFinance/zendesk-flutter-plugin#31]
I have created a fork and trying to run on ios and android emulators.  This runs perfectly on ios emulator.  However, for android emulator, I get the following error:

MainActivity.java:11: error: incompatible types: MainActivity cannot be converted to PluginRegistry
    GeneratedPluginRegistrant.registerWith(this);

**Comment by sudoFerraz** [comment]
Can you do flutter doctor -v and copy the output here please

**Comment by lkettwig** [comment]
Yes thank you.

[✓] Flutter (Channel unknown, v1.17.5, on Mac OS X 10.15.6 19G2021, locale
    en-US)
    • Flutter version 1.17.5 at /Users/lkettwig/development/flutter
    • Framework revision 8af6b2f038 (7 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/lkettwig/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • sdk gphone x86 arm • emulator-5554                            •
      android-x86 • Android 11 (API 30) (emulator)
    • iPhone             • 0e1638cce66a66638b38dcd5e20929d1958a45a6 • ios
      • iOS 13.6

• No issues found!

**Comment by sudoFerraz** [comment]
Have you tried to extend your main activity into flutter fragment activity? @lkettwig

**Comment by sudoFerraz** [comment]
Closing this as no updates were giving, will be happy to reopen if there is any update or resolution.
