### ISSUE TITLE
Agent joining and leaving won't send data to the stream

### ISSUE THREAD

**Issue by mateusfccp** [ChangeFinance/zendesk-flutter-plugin#32]
Hello. First of all, thanks for this great plugin, it's currently the only one that can solve the requirements of our application.

I have listened to the chat items stream like in the `example` provided. Every time someone sends a message it will correctly add a list of the messages to the stream.

However, if an agent enters or leaves the chat it won't add any `MEMBER_JOIN` nor `MEMBER_LEAVE` messages to the chat items list.

Thus, I can't track the agents currently in the chat.

This problem is happening to me when testing on iOS Simulator.

**Comment by sudoFerraz** [comment]
@mateusfccp please debug the stream to check the messages added to them, I also still use this package on my application, and we can indeed check when a agent enters or leave the live chat. I am not sure if these are the correct messages, if I'm not mistaken it is agent_online or something like that. Please also double check your zendesk configuration, it might be something there. If you still could not find let me know and I will check it for you during the weekend
Cheers :)

**Comment by sudoFerraz** [comment]
Closing this as no updates were giving, will be happy to reopen if there is any update or resolution.
